language: php

php:
  - 5.3
#  - 5.4 //run only with php5.3 to reduce the build time
env:
  - DB=mysql

before_install:
  - sudo apt-get install node
before_script:
# install apache and configure host
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/public,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "/DocumentRoot/i\ServerName reqman.dev" /etc/apache2/sites-available/default
  - sudo cat /etc/apache2/sites-available/default
  - echo "127.0.0.1 reqman.dev" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart
# Increase limit of api calls to composer
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
#install packages
  - composer self-update
  - composer install --dev --prefer-dist
  - cp app/api.php public/api.php
# Apply migrations
  - mysql -e 'create database test_reqman;'
  - php app/console.php knp:migration:migrate
# run x
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#install selenium
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
# - sleep 5 no need to do that now
#install web app
  - npm install -g grunt bower
script:
  - ./bin/behat
  - bower install
  - grunt test
